---
name: Python

on:
  pull_request:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.9

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y software-properties-common jq make
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install --no-install-recommends -y python${PYTHON_VERSION} python${PYTHON_VERSION}-venv python3-pip
      - name: Install dependencies
        run: make venv
      - name: Lint
        run: make lint
      - name: Build package
        run: make build
      - name: Publish package to PyPI
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]] && [[ "$GITHUB_REF_NAME" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]; then
            make upload/pypi
          fi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
